# Generated by Django 5.1.6 on 2025-02-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('numero', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('vitorias', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Baralho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartas', models.ManyToManyField(to='cardgame.carta')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='em andamento', max_length=20)),
                ('jogador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_jogador1', to='cardgame.jogador')),
                ('jogador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_jogador2', to='cardgame.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Jogada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardgame.carta')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardgame.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardgame.partida')),
            ],
        ),
    ]
