# Generated by Django 5.1.6 on 2025-03-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baralho',
            name='partida',
        ),
        migrations.AddField(
            model_name='baralho',
            name='jogador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carta',
            name='tipo',
            field=models.CharField(choices=[('fogo', 'Fogo'), ('agua', 'Água'), ('neve', 'Neve')], max_length=20),
        ),
    ]
